services:
  worker-1:
    build:
      context: .
      dockerfile: Dockerfile.nix
    container_name: worker-1
    ports:
      - "2221:22"

  worker-2:
    build:
      context: .
      dockerfile: Dockerfile.nix
    container_name: worker-2
    ports:
      - "2222:22"

  worker-3:
    build:
      context: .
      dockerfile: Dockerfile.nix
    container_name: worker-3
    ports:
      - "2223:22"